In [6]:
import cv2
import numpy as np

#创建两张测试性图片
img1 = np.array([[100,200], [50,250]], dtype=np.uint8)
img2 = np.array([[100,100], [50,50]], dtype=np.uint8)

#普通numpy加法会溢出
add_numpy = img1 + img2
print("Numpy加法结果:\n", add_numpy)

#Opencv饱和加法（超过255截断为255）
add_cv = cv2.add(img1, img2)
print("Opencv加法结果:\n", add_cv)



Numpy加法结果:
 [[200  44]
 [100  44]]
Opencv加法结果:
 [[200 255]
 [100 255]]


In [7]:
import cv2
import numpy as np
# 创建两张测试图像
img1 = np.uint8([[100, 200], [50, 250]])
img2 = np.uint8([[100, 100], [50, 50]])
# 普通numpy加法（会发生溢出）
add_numpy = img1 + img2
print("Numpy加法结果:\n", add_numpy)
# OpenCV饱和加法（超过255截断为255）
add_cv = cv2.add(img1, img2)
print("OpenCV加法结果:\n", add_cv)

Numpy加法结果:
 [[200  44]
 [100  44]]
OpenCV加法结果:
 [[200 255]
 [100 255]]
